### ISSUE TITLE
Questions about proper usage of setuptools-protobuf

### ISSUE THREAD

**Issue by vhaldemar** [jelmer/setuptools-protobuf#21]
Hello!
I am working on a nice protobuf build process in my project and bumped into your project, which looks very promising.
The problem is, I am new to all this PEP-517 stuff and I can't figure out how I can do several things and can I do it at all:
1) I need to include builded proto into sdist, but as far I can see, you are injecting into "build" subcommands, so am I understanding correctly that I need to inject something somewhere myself?
2) I want to build proto while editable installation too.
3) I need to figure out my protobufs list dynamically, and maybe even move protobuf files into my project tree while building process.
4) And I can't figure out what I need to write in my pyproject.toml to start using setuptools-protobuf.

I would very much appreciate your consultation, thanks in advance!

**Comment by vhaldemar** [comment]
> See the example in README; however, you won't be able to use this if you need to dynamically figure out the protos to compile. In that case, your only option is passing in options in setup.py.

I believe you are missing some readme about `[distutils.*]` sections in `pyproject.toml` to use your shiny new `setuptools_protofub.pyprojecttoml_config` and get rid of setup.py completely. I am trying to figure out, that maybe I can define some PEP-517 build entry point in my pyproject.toml where I can call your code.

I leave for one week's vacation and will be back to this task in 8-9 days.
Maybe you will issue a new release at that time and I will be able to contribute something.

Thanks!

**Comment by jelmer** [comment]
There shouldn't be a need to explicitly add anything else in your pyproject.toml; installing setuptools_protobuf itself (don't just put in $PYTHONPATH) using pip should install all the right entrypoints.

A couple of my projects (e.g. https://github.com/jelmer/disperse/blob/main/setup.py) do exactly this.

**Comment by jelmer** [comment]
Closing this since I think I've addressed the original questions; please reopen and comment if you'd like me to expand on anything.
